/** @type {string[]} */
export const FALLBACK_TASKS: string[] = [
  "Morning stretch",
  "Hydrate with 2L water",
  "Read 20 pages",
  "Cook a new recipe",
  "Declutter one drawer",
  "Walk 8,000 steps",
  "Call a friend",
  "Meditate for 10 min",
  "Journal gratitude",
  "Try a new playlist",
  "No-sugar afternoon",
  "Sunset photo",
  "Plan tomorrow",
  "Learn one new word",
  "Clean your desk",
  "Do 20 squats",
  "Screen-free hour",
  "Pack healthy lunch",
  "Practice a hobby",
  "Do a random kindness",
  "Take a deep-breath break",
  "Review your goals",
  "Make your bed",
  "Write a positive note",
  "Dance to one song",
];
